### ISSUE TITLE
Global dictionary issues

### ISSUE THREAD

**Issue by jw3** [jw3/microkf-ansible#3]
When using Istio 1.3.6 integrated with Microk8s

```
INTERNAL:inconsistent global dictionary versions used: mixer knows 221 words, caller knows 222
```

Using the KF Istio works.

**Comment by jw3** [comment]
https://github.com/istio/istio/blob/master/mixer/pkg/api/grpcServer.go#L87

**Comment by alexwennerberg** [comment]
I'm encountering this as well using kfserving: https://github.com/kubeflow/kfserving/issues/634

Interested in any resolution you find

**Comment by Manvi07** [comment]
@jw3 How did you solve this?

**Comment by hexiaoliangRick** [comment]
@jw3 @alexwennerberg  any solutions here?

**Comment by jw3** [comment]
Didnt see the traffic here... trying to recall what it was...

Looks like using istio provided by KF instead of using microk8s istio.
